version: '3.7'

services:
  discord:
    build: .
    container_name: ${CONTAINER_NAME}
    working_dir: /usr/src/app
    user: root
    entrypoint: tail -f /dev/null
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      TZ: 'Asia/Seoul'