version: '3.7'

services:
  discord:
    build: .
    container_name: ${CONTAINER_NAME}
    user: root
    entrypoint: sh command.sh
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      TZ: 'Asia/Seoul'